# Generated by Django 4.2.2 on 2023-07-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_bids_category_comments_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
