# Generated by Django 4.2.2 on 2023-07-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_highest_bid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
